### ISSUE TITLE
Not compatible with new version of Karma.

### ISSUE THREAD

**Issue by BillArmstrong** [david-driscoll/karma-msbuild-reporter#1]
After upgrading to Karma version 0.12.5, I started getting this error:

Cannot call method 'push' of undefined.

After searching Google for this error, I found the same error being reported for karma-mocha-reporter. In the issue thread it was indicated that the reporter API changed in Karma 11, and that the reporter had to be updated to work with the new API.

Please update this reporter to work with the new API.

Thanks.

**Comment by david-driscoll** [comment]
Sorry I didn't get to your message earlier!

I will see if I can get to this, this weekend, I have some new stuff that I'm working on for integrating Node, Npm, Bower, Karma, etc into Visual Studio using NuGet and MSBuild.  So I'll make sure to setup a test with Karma, and bring in the reporter and fix it for 0.12

**Comment by BillArmstrong** [comment]
No worries. I've already fixed it by looking at what was changed in karma-mocha-reporter. I meant to submit a pull-request, but I have not gotten around to it. I'll try to do it if I get some time.

**Comment by tomhaywood** [comment]
Hi is anyone able to look at this, or let me know what the required change is.. cheers for your help!!

**Comment by BillArmstrong** [comment]
I submitted a pull request with the fix. Tom you should be able to access the fix from there.

Bill

**Comment by tomhaywood** [comment]
Thankyou both!
